import { NavLink, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { Grid2X2, Plus, Package, UserCircle, MessageCircle, Settings, LogOut, X } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { api } from "../api/client";
import { socket } from "../chat/socket";

export default function NavBar() {
  const { user, logout } = useAuth(), navigate = useNavigate();
  const [unread, setUnread] = useState(0), [settingsOpen, setSettingsOpen] = useState(false);
  useEffect(() => { if (!user) return; const refresh = () => api.conversations().then(items => setUnread(items.reduce((n, item) => n + item.unreadCount, 0))).catch(() => {}); socket.auth = { token: localStorage.getItem("claimco_token") }; if (!socket.connected) socket.connect(); socket.on("new_message", refresh); window.addEventListener("conversation-read", refresh); refresh(); const timer = setInterval(refresh, 3000); return () => { socket.off("new_message", refresh); window.removeEventListener("conversation-read", refresh); clearInterval(timer); }; }, [user]);
  return <><header className="site-header"><div className="site-header-inner"><NavLink className="site-logo" to="/board">Bruno <span>Sells</span></NavLink><span className="site-tagline">Find it around Brown.</span><div className="site-header-actions">{user ? <><NavLink className="account-link" to="/account"><UserCircle size={20} /><span>{user.name}</span></NavLink><button className="settings-button" aria-label="Open settings" onClick={() => setSettingsOpen(true)}><Settings size={20} /></button></> : <><NavLink className="guest-login-link" to="/login">Log in</NavLink><NavLink className="btn btn-complete guest-join-link" to="/login?mode=register">Join</NavLink></>}</div></div></header>
    <nav className="tabs" aria-label="Marketplace navigation"><NavLink to="/board" className={({ isActive }) => `tab-btn ${isActive ? "active" : ""}`}><Grid2X2 size={17} /> <span>Explore</span></NavLink><NavLink to="/post" className={({ isActive }) => `tab-btn ${isActive ? "active" : ""}`}><Plus size={18} /> <span>Sell an item</span></NavLink><NavLink to="/mine" className={({ isActive }) => `tab-btn ${isActive ? "active" : ""}`}><Package size={17} /> <span>My items</span></NavLink><NavLink to="/messages" className={({ isActive }) => `tab-btn ${isActive ? "active" : ""}`}><MessageCircle size={17} /> <span>Messages</span>{unread > 0 && <span className="message-unread-badge">{unread}</span>}</NavLink></nav>
    {user && settingsOpen && <div className="settings-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) setSettingsOpen(false); }}><section className="settings-dialog" role="dialog" aria-modal="true" aria-label="Settings"><div className="settings-dialog-header"><h2>Settings</h2><button className="settings-close" aria-label="Close settings" onClick={() => setSettingsOpen(false)}><X size={20} /></button></div><button className="settings-help-option" onClick={() => { setSettingsOpen(false); navigate("/help"); }}>Help & FAQs</button><button className="settings-logout" onClick={() => { logout(); window.location.replace("/"); }}><LogOut size={17} /> Log out</button></section></div>}
  </>;
}
