import { Link } from "react-router-dom";

const contact = <a href="mailto:collegehillmarket1@gmail.com">collegehillmarket1@gmail.com</a>;

export function Terms() { return <main className="content legal-page"><h1>Terms of use</h1><p>Last updated September 28, 2026.</p><p>College Hill Market is an independent marketplace for local students. It is not affiliated with Brown University or Rhode Island School of Design. By creating an account or posting content, you agree to these terms.</p><h2>Who can use it</h2><p>Accounts require verification with an approved school email. Keep your account and verification codes secure. Listings and messages must be honest and lawful.</p><h2>Listings and conduct</h2><p>Only list items you may legally sell. Do not post counterfeit, stolen, dangerous, illegal, or otherwise prohibited goods. Do not harass, threaten, impersonate, spam, or scam anyone. We may remove content or suspend accounts that violate these rules.</p><h2>Transactions</h2><p>Buyers and sellers arrange handoff and payment directly. College Hill Market does not process payments, hold money, guarantee items, or mediate transactions. Check items and meet safely before paying.</p><h2>Reports</h2><p>Use the report control on a listing, profile, or message to flag a problem. You may block another user. For urgent safety concerns, contact local authorities. Send other concerns to {contact}.</p><h2>Changes and contact</h2><p>We may update these terms and show the updated date here. Continued use after an update means you accept the updated terms. Questions: {contact}.</p><p><Link to="/privacy">Privacy policy</Link></p></main>; }

export function Privacy() { return <main className="content legal-page"><h1>Privacy policy</h1><p>Last updated September 28, 2026.</p><p>Contact: {contact}.</p><h2>Information we use</h2><p>We collect your name, school email, phone number, year, area of study, optional profile details and photo, listings and photos, messages, reports, blocks, and verification records. The app may collect a device push token after you allow notifications. The website uses privacy focused Umami analytics for visits and selected marketplace actions. We do not sell personal information.</p><h2>How we use it</h2><p>We verify school eligibility, operate listings and chat, send verification codes and message alerts, handle abuse reports, measure marketplace usage, and protect the service. We share profile and listing details with visitors, and messages with their participants. Service providers host the database, images, email, analytics, and optional push delivery.</p><h2>Retention and deletion</h2><p>Listings and chats remain while an account is active. You can delete your account from Account settings. Deletion removes your profile, listings, chats, and stored images from active systems; limited backups and records needed for legal or safety reasons may persist for a limited period. Report records may retain the reported content identifier and reason without your account details.</p><h2>Your choices</h2><p>You can edit your profile, remove listings, block users, and turn off push notifications in device settings. You may request access or deletion at {contact}. See <Link to="/delete-account">account deletion instructions</Link>.</p><h2>Security and changes</h2><p>We use email verification, authenticated sessions, and access controls. No online service is risk free. We will update this page when practices materially change.</p></main>; }

export function DeleteAccountInfo() { return <main className="content legal-page"><h1>Delete your account</h1><p>Sign in, open <Link to="/account">Account</Link>, and choose Delete account. This removes your profile, listings, conversations, messages, and stored images from active systems. If you cannot sign in, email {contact} from your registered address with “Delete my account” in the subject. We will verify your request before acting.</p><p>Some backup copies and limited safety or legal records may remain for a limited period. See our <Link to="/privacy">privacy policy</Link>.</p></main>; }
