const path = require("path");
const fs = require("fs");
const Database = require("better-sqlite3");
const { Pool } = require("pg");

function translateSqliteToPostgres(sql) {
    if (!sql || typeof sql !== "string") return sql;

    let paramIndex = 0;
    let normalized = sql.replace(/\?/g, () => {
        paramIndex += 1;
        return `$${paramIndex}`;
    });

    normalized = normalized
        .replace(/datetime\(\s*'now'\s*\)/gi, "NOW()")
        .replace(/datetime\(\s*'now'\s*,\s*'localtime'\s*\)/gi, "CURRENT_TIMESTAMP")
        .replace(/datetime\(\s*'now'\s*,\s*'localtime'\s*,\s*'\+10 minutes'\s*\)/gi, "CURRENT_TIMESTAMP + INTERVAL '10 minutes'")
        .replace(/datetime\(\s*replace\(\s*([^,]+?)\s*,\s*'T',\s*' '\s*\)\s*\)/gi, "replace($1, 'T', ' ')::timestamptz")
        .replace(/datetime\(\s*replace\(\s*([^,]+?)\s*,\s*'T',\s*' '\s*\)\s*\|\|\s*CASE\s+WHEN\s+instr\(([^)]+?),\s*'T'\s*\)\s*=\s*0\s+THEN\s*' 23:59:59'\s+ELSE\s*''\s+END\s*\)/gi, "(replace($1, 'T', ' ') || CASE WHEN POSITION('T' IN $2) = 0 THEN ' 23:59:59' ELSE '' END)::timestamptz")
        .replace(/datetime\(\s*(\$\d+)\s*,\s*'auto'\s*\)/gi, "($1)::timestamptz")
        .replace(/datetime\(\s*(\$\d+)\s*\)/gi, "($1)::timestamptz")
        .replace(/date\(\s*'now'\s*,\s*'localtime'\s*\)/gi, "CURRENT_DATE")
        .replace(/date\(\s*(\$\d+)\s*\)/gi, "DATE($1)")
        .replace(/\binstr\s*\(\s*([^,]+?)\s*,\s*'([^']+)'\s*\)/gi, "POSITION('$2' IN $1)")
        .replace(/\bINTEGER PRIMARY KEY AUTOINCREMENT\b/gi, "BIGSERIAL PRIMARY KEY")
        .replace(/\bAUTOINCREMENT\b/gi, "GENERATED BY DEFAULT AS IDENTITY")
        .replace(/\bINTEGER PRIMARY KEY\b/gi, "BIGINT PRIMARY KEY");

    normalized = normalized.replace(
        /\b(created_at|claimed_at|completed_at|cancelled_at|used_at|email_verified_at|consumed_at|read_at|expires_at)\s+TEXT\b/gi,
        "$1 TIMESTAMPTZ"
    );

    normalized = normalized.replace(
        /julianday\(\s*'now'\s*\)\s*-\s*julianday\(\s*([^)]+)\s*\)\s*<\s*1/gi,
        "$1 > NOW() - INTERVAL '1 day'"
    );

    return normalized;
}

function applyReturningId(sql) {
    if (!/^\s*INSERT\s+/i.test(sql) || /\bRETURNING\b/i.test(sql)) return sql;
    return `${sql.trim()} RETURNING id`;
}

function createPostgresDb() {
    const pool = new Pool({
        connectionString: process.env.DATABASE_URL,
        ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : undefined,
    });

    const qb = async (sql, params = []) => {
        const normalized = translateSqliteToPostgres(sql);
        const querySql = applyReturningId(normalized);
        return pool.query(querySql, params);
    };

    const schemaSql = fs.readFileSync(path.join(__dirname, "schema.sql"), "utf8");
    const schemaStatements = schemaSql
        .split(/;\s*(?=(?:[^'"]|'[^']*'|\"[^\"]*\")*$)/)
        .map((statement) => statement.trim())
        .filter(Boolean)
        .map((statement) => translateSqliteToPostgres(statement));

    const ready = (async () => {
        const legacy = await pool.query("SELECT to_regclass('public.tasks') AS old_table");
        if (legacy.rows[0].old_table) {
            await pool.query("DROP TABLE IF EXISTS notifications, reviews, task_applications, service_purchases, messages, conversations, tasks, services, support_messages CASCADE");
        }
        for (const statement of schemaStatements) await pool.query(statement);
        await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS online_status TEXT NOT NULL DEFAULT 'offline'");
        await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ");
        await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image_public_id TEXT");
        await pool.query("ALTER TABLE users DROP COLUMN IF EXISTS stripe_account_id");
        await pool.query("ALTER TABLE users DROP COLUMN IF EXISTS stripe_onboarded");
        await pool.query("INSERT INTO approved_domains (domain, school_name) VALUES ('brown.edu', 'Brown University') ON CONFLICT (domain) DO NOTHING");
    })().catch((error) => {
        console.error("Postgres schema initialization failed:", error);
        throw error;
    });

    return {
        ready,
        prepare(sql) {
            return {
                get: async (...params) => {
                    const result = await qb(sql, params);
                    return result.rows[0] ?? undefined;
                },
                all: async (...params) => {
                    const result = await qb(sql, params);
                    return result.rows;
                },
                run: async (...params) => {
                    const result = await qb(sql, params);
                    const lastInsertRowid = result.rows?.[0]?.id ?? null;
                    return {
                        changes: result.rowCount || 0,
                        lastInsertRowid,
                    };
                },
            };
        },
        exec: async (sql) => {
            const statements = sql.split(/;\s*(?=(?:[^'\"]|'[^']*'|\"[^\"]*\")*$)/).map((s) => s.trim()).filter(Boolean);
            for (const statement of statements) {
                await pool.query(translateSqliteToPostgres(statement));
            }
        },
        transaction: async (fn) => {
            const client = await pool.connect();
            try {
                await client.query("BEGIN");
                const txDb = {
                    prepare(sql) {
                        return {
                            get: async (...params) => {
                                const result = await client.query(translateSqliteToPostgres(applyReturningId(sql)), params);
                                return result.rows[0] ?? undefined;
                            },
                            all: async (...params) => {
                                const result = await client.query(translateSqliteToPostgres(sql), params);
                                return result.rows;
                            },
                            run: async (...params) => {
                                const result = await client.query(translateSqliteToPostgres(applyReturningId(sql)), params);
                                return {
                                    changes: result.rowCount || 0,
                                    lastInsertRowid: result.rows?.[0]?.id ?? null,
                                };
                            },
                        };
                    },
                };
                const result = await fn(txDb);
                await client.query("COMMIT");
                return result;
            } catch (error) {
                await client.query("ROLLBACK");
                throw error;
            } finally {
                client.release();
            }
        },
    };
}

function setupSqliteDb() {
    const DB_PATH = process.env.DATABASE_PATH || path.join(__dirname, "..", "..", "dev.db");
    const db = new Database(DB_PATH);

    db.pragma("journal_mode = WAL");
    db.pragma("foreign_keys = ON");

    const legacy = db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'tasks'").get();
    if (legacy) {
        db.pragma("foreign_keys = OFF");
        db.exec("DROP TABLE IF EXISTS notifications; DROP TABLE IF EXISTS reviews; DROP TABLE IF EXISTS task_applications; DROP TABLE IF EXISTS service_purchases; DROP TABLE IF EXISTS messages; DROP TABLE IF EXISTS conversations; DROP TABLE IF EXISTS tasks; DROP TABLE IF EXISTS services; DROP TABLE IF EXISTS support_messages;");
        db.pragma("foreign_keys = ON");
    }
    db.exec(fs.readFileSync(path.join(__dirname, "schema.sql"), "utf8"));
    const userColumns = db.prepare("PRAGMA table_info(users)").all().map((column) => column.name);
    for (const column of ["stripe_account_id", "stripe_onboarded"]) {
        if (userColumns.includes(column)) db.exec(`ALTER TABLE users DROP COLUMN ${column}`);
    }
    for (const [column, definition] of [["year", "TEXT"], ["concentration", "TEXT"], ["about_me", "TEXT"], ["profile_image", "TEXT"], ["profile_image_public_id", "TEXT"], ["school_email", "TEXT"], ["phone_number", "TEXT"], ["email_verified_at", "TEXT"], ["status", "TEXT DEFAULT 'active'"], ["online_status", "TEXT NOT NULL DEFAULT 'offline'"], ["last_seen_at", "TEXT"]]) {
        if (!userColumns.includes(column)) db.exec(`ALTER TABLE users ADD COLUMN ${column} ${definition}`);
    }
    if (!db.prepare("SELECT domain FROM approved_domains WHERE domain = 'brown.edu'").get()) {
        db.prepare("INSERT INTO approved_domains (domain, school_name) VALUES (?, ?)").run("brown.edu", "Brown University");
    }
    db.transaction = async (fn) => {
        db.exec("BEGIN");
        try {
            const result = await fn(db);
            db.exec("COMMIT");
            return result;
        } catch (error) {
            db.exec("ROLLBACK");
            throw error;
        }
    };
    return db;
}

const dbMode = process.env.DATABASE_URL ? "postgres" : "sqlite";
console.log(`[db] Using database mode: ${dbMode}`);

const db = dbMode === "postgres" ? createPostgresDb() : setupSqliteDb();

module.exports = db;
module.exports.translateSqliteToPostgres = translateSqliteToPostgres;
