const path = require("path");
const fs = require("fs");
const Database = require("better-sqlite3");
const { Pool } = require("pg");

function translateSqliteToPostgres(sql) {
    if (!sql || typeof sql !== "string") return sql;

    let paramIndex = 0;
    let normalized = sql.replace(/\?/g, () => {
        paramIndex += 1;
        return `$${paramIndex}`;
    });

    normalized = normalized
        .replace(/datetime\(\s*'now'\s*\)/gi, "NOW()")
        .replace(/datetime\(\s*'now'\s*,\s*'localtime'\s*\)/gi, "CURRENT_TIMESTAMP")
        .replace(/datetime\(\s*'now'\s*,\s*'localtime'\s*,\s*'\+10 minutes'\s*\)/gi, "CURRENT_TIMESTAMP + INTERVAL '10 minutes'")
        .replace(/datetime\(\s*replace\(\s*([^,]+?)\s*,\s*'T',\s*' '\s*\)\s*\)/gi, "replace($1, 'T', ' ')::timestamptz")
        .replace(/datetime\(\s*replace\(\s*([^,]+?)\s*,\s*'T',\s*' '\s*\)\s*\|\|\s*CASE\s+WHEN\s+instr\(([^)]+?),\s*'T'\s*\)\s*=\s*0\s+THEN\s*' 23:59:59'\s+ELSE\s*''\s+END\s*\)/gi, "(replace($1, 'T', ' ') || CASE WHEN POSITION('T' IN $2) = 0 THEN ' 23:59:59' ELSE '' END)::timestamptz")
        .replace(/datetime\(\s*(\$\d+)\s*,\s*'auto'\s*\)/gi, "($1)::timestamptz")
        .replace(/datetime\(\s*(\$\d+)\s*\)/gi, "($1)::timestamptz")
        .replace(/date\(\s*'now'\s*,\s*'localtime'\s*\)/gi, "CURRENT_DATE")
        .replace(/date\(\s*(\$\d+)\s*\)/gi, "DATE($1)")
        .replace(/\binstr\s*\(\s*([^,]+?)\s*,\s*'([^']+)'\s*\)/gi, "POSITION('$2' IN $1)")
        .replace(/\bINTEGER PRIMARY KEY AUTOINCREMENT\b/gi, "BIGSERIAL PRIMARY KEY")
        .replace(/\bAUTOINCREMENT\b/gi, "GENERATED BY DEFAULT AS IDENTITY")
        .replace(/\bINTEGER PRIMARY KEY\b/gi, "BIGINT PRIMARY KEY");

    normalized = normalized.replace(
        /\b(created_at|claimed_at|completed_at|cancelled_at|used_at|email_verified_at|consumed_at|read_at|expires_at)\s+TEXT\b/gi,
        "$1 TIMESTAMPTZ"
    );

    normalized = normalized.replace(
        /julianday\(\s*'now'\s*\)\s*-\s*julianday\(\s*([^)]+)\s*\)\s*<\s*1/gi,
        "$1 > NOW() - INTERVAL '1 day'"
    );

    return normalized;
}

function applyReturningId(sql) {
    if (!/^\s*INSERT\s+/i.test(sql) || /\bRETURNING\b/i.test(sql)) return sql;
    return `${sql.trim()} RETURNING id`;
}

function createPostgresDb() {
    const pool = new Pool({
        connectionString: process.env.DATABASE_URL,
        ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : undefined,
    });

    const qb = async (sql, params = []) => {
        const normalized = translateSqliteToPostgres(sql);
        const querySql = applyReturningId(normalized);
        return pool.query(querySql, params);
    };

    const schemaSql = fs.readFileSync(path.join(__dirname, "schema.sql"), "utf8");
    const schemaStatements = schemaSql
        .split(/;\s*(?=(?:[^'"]|'[^']*'|\"[^\"]*\")*$)/)
        .map((statement) => statement.trim())
        .filter(Boolean)
        .map((statement) => translateSqliteToPostgres(statement));

    const supportMessagesSql = `
    CREATE TABLE IF NOT EXISTS support_messages (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT,
      email TEXT,
      message TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      resolved INTEGER NOT NULL DEFAULT 0
    )
  `;
    const ready = (async () => {
        for (const statement of schemaStatements) {
            await pool.query(statement);
        }
        await pool.query(
            "INSERT INTO approved_domains (domain, school_name) VALUES ('brown.edu', 'Brown University') ON CONFLICT (domain) DO NOTHING"
        );
        await pool.query(translateSqliteToPostgres(supportMessagesSql));
    })().catch((error) => {
        console.error("Postgres schema initialization failed:", error);
        throw error;
    });

    return {
        ready,
        prepare(sql) {
            return {
                get: async (...params) => {
                    const result = await qb(sql, params);
                    return result.rows[0] ?? undefined;
                },
                all: async (...params) => {
                    const result = await qb(sql, params);
                    return result.rows;
                },
                run: async (...params) => {
                    const result = await qb(sql, params);
                    const lastInsertRowid = result.rows?.[0]?.id ?? null;
                    return {
                        changes: result.rowCount || 0,
                        lastInsertRowid,
                    };
                },
            };
        },
        exec: async (sql) => {
            const statements = sql.split(/;\s*(?=(?:[^'\"]|'[^']*'|\"[^\"]*\")*$)/).map((s) => s.trim()).filter(Boolean);
            for (const statement of statements) {
                await pool.query(translateSqliteToPostgres(statement));
            }
        },
        transaction: async (fn) => {
            const client = await pool.connect();
            try {
                await client.query("BEGIN");
                const txDb = {
                    prepare(sql) {
                        return {
                            get: async (...params) => {
                                const result = await client.query(translateSqliteToPostgres(applyReturningId(sql)), params);
                                return result.rows[0] ?? undefined;
                            },
                            all: async (...params) => {
                                const result = await client.query(translateSqliteToPostgres(sql), params);
                                return result.rows;
                            },
                            run: async (...params) => {
                                const result = await client.query(translateSqliteToPostgres(applyReturningId(sql)), params);
                                return {
                                    changes: result.rowCount || 0,
                                    lastInsertRowid: result.rows?.[0]?.id ?? null,
                                };
                            },
                        };
                    },
                };
                const result = await fn(txDb);
                await client.query("COMMIT");
                return result;
            } catch (error) {
                await client.query("ROLLBACK");
                throw error;
            } finally {
                client.release();
            }
        },
    };
}

function setupSqliteDb() {
    const DB_PATH = process.env.DATABASE_PATH || path.join(__dirname, "..", "..", "dev.db");
    const db = new Database(DB_PATH);

    db.pragma("journal_mode = WAL");
    db.pragma("foreign_keys = ON");

    const schema = fs.readFileSync(path.join(__dirname, "schema.sql"), "utf8");
    db.exec(schema);

    const taskColumns = db.prepare("PRAGMA table_info(tasks)").all().map((column) => column.name);
    if (!taskColumns.includes("requester_anonymous")) {
        db.exec("ALTER TABLE tasks ADD COLUMN requester_anonymous INTEGER NOT NULL DEFAULT 0");
    }
    if (!taskColumns.includes("worker_anonymous")) {
        db.exec("ALTER TABLE tasks ADD COLUMN worker_anonymous INTEGER NOT NULL DEFAULT 0");
    }
    if (!taskColumns.includes("images_json")) {
        db.exec("ALTER TABLE tasks ADD COLUMN images_json TEXT NOT NULL DEFAULT '[]'");
    }
    if (!taskColumns.includes("scheduled_at")) {
        db.exec("ALTER TABLE tasks ADD COLUMN scheduled_at TEXT");
    }
    if (!taskColumns.includes("location")) {
        db.exec("ALTER TABLE tasks ADD COLUMN location TEXT");
    }
    if (!taskColumns.includes("notes")) {
        db.exec("ALTER TABLE tasks ADD COLUMN notes TEXT NOT NULL DEFAULT ''");
    }
    if (!taskColumns.includes("requester_completed")) {
        db.exec("ALTER TABLE tasks ADD COLUMN requester_completed INTEGER NOT NULL DEFAULT 0");
    }
    if (!taskColumns.includes("worker_completed")) {
        db.exec("ALTER TABLE tasks ADD COLUMN worker_completed INTEGER NOT NULL DEFAULT 0");
    }
    db.exec("UPDATE tasks SET requester_completed = 1, worker_completed = 1 WHERE status = 'done'");

    const serviceColumns = db.prepare("PRAGMA table_info(services)").all().map((column) => column.name);
    if (!serviceColumns.includes("images_json")) {
        db.exec("ALTER TABLE services ADD COLUMN images_json TEXT NOT NULL DEFAULT '[]'");
    }

    const taskApplicationColumns = db.prepare("PRAGMA table_info(task_applications)").all().map((column) => column.name);
    if (!taskApplicationColumns.includes("request_note")) {
        db.exec("ALTER TABLE task_applications ADD COLUMN request_note TEXT NOT NULL DEFAULT ''");
    }

    db.exec(`
    CREATE TABLE IF NOT EXISTS support_messages (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT,
      email TEXT,
      message TEXT NOT NULL,
      created_at TEXT DEFAULT (datetime('now')),
      resolved INTEGER DEFAULT 0
    )
  `);

    const serviceTableSql = db.prepare("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'services'").get()?.sql || "";
    if (!serviceTableSql.includes("'academic'")) {
        db.pragma("foreign_keys = OFF");
        db.exec(`
      BEGIN;
      CREATE TABLE services_migrated (
        id            TEXT PRIMARY KEY,
        category      TEXT NOT NULL CHECK (category IN ('academic', 'careers', 'creative', 'other')),
        title         TEXT NOT NULL,
        description   TEXT NOT NULL DEFAULT '',
        images_json   TEXT NOT NULL DEFAULT '[]',
        price_cents   INTEGER NOT NULL CHECK (price_cents > 0),
        price_unit    TEXT NOT NULL DEFAULT 'per booking',
        provider_id   TEXT NOT NULL REFERENCES users(id),
        status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
        created_at    TEXT NOT NULL DEFAULT (datetime('now'))
      );
      INSERT INTO services_migrated (id, category, title, description, images_json, price_cents, price_unit, provider_id, status, created_at)
      SELECT id,
        CASE category
          WHEN 'moveout' THEN 'other'
          WHEN 'errand' THEN 'other'
          WHEN 'event' THEN 'other'
          ELSE category
        END,
        title, description, images_json, price_cents, price_unit, provider_id, status, created_at
      FROM services;
      DROP TABLE services;
      ALTER TABLE services_migrated RENAME TO services;
      CREATE INDEX IF NOT EXISTS idx_services_status ON services(status);
      CREATE INDEX IF NOT EXISTS idx_services_provider ON services(provider_id);
      COMMIT;
    `);
        db.pragma("foreign_keys = ON");
    }

    const userColumns = db.prepare("PRAGMA table_info(users)").all().map((column) => column.name);
    if (!userColumns.includes("year")) {
        db.exec("ALTER TABLE users ADD COLUMN year TEXT");
    }
    if (!userColumns.includes("concentration")) {
        db.exec("ALTER TABLE users ADD COLUMN concentration TEXT");
    }
    if (!userColumns.includes("about_me")) {
        db.exec("ALTER TABLE users ADD COLUMN about_me TEXT");
    }
    if (!userColumns.includes("profile_image")) {
        db.exec("ALTER TABLE users ADD COLUMN profile_image TEXT");
    }
    if (!userColumns.includes("school_email")) {
        db.exec("ALTER TABLE users ADD COLUMN school_email TEXT UNIQUE");
    }
    if (!userColumns.includes("phone_number")) {
        db.exec("ALTER TABLE users ADD COLUMN phone_number TEXT UNIQUE");
    }
    if (!userColumns.includes("email_verified_at")) {
        db.exec("ALTER TABLE users ADD COLUMN email_verified_at TEXT");
    }
    if (!userColumns.includes("status")) {
        db.exec("ALTER TABLE users ADD COLUMN status TEXT DEFAULT 'active'");
        db.exec("UPDATE users SET status = 'active' WHERE status IS NULL");
    }

    const domainsCount = db.prepare("SELECT COUNT(*) as count FROM approved_domains").get().count;
    if (domainsCount === 0) {
        db.prepare("INSERT INTO approved_domains (domain, school_name) VALUES (?, ?)").run('brown.edu', 'Brown University');
    }

    const purchaseColumns = db.prepare("PRAGMA table_info(service_purchases)").all().map((column) => column.name);
    if (!purchaseColumns.includes("confirmation_status")) {
        db.exec("ALTER TABLE service_purchases ADD COLUMN confirmation_status TEXT NOT NULL DEFAULT 'confirmed'");
    }
    if (!purchaseColumns.includes("request_note")) {
        db.exec("ALTER TABLE service_purchases ADD COLUMN request_note TEXT NOT NULL DEFAULT ''");
    }

    const reviewColumns = db.prepare("PRAGMA table_info(reviews)").all().map((column) => column.name);
    if (reviewColumns.length && !reviewColumns.includes("anonymous")) {
        db.exec("ALTER TABLE reviews ADD COLUMN anonymous INTEGER NOT NULL DEFAULT 0");
    }

    const messageColumns = db.prepare("PRAGMA table_info(messages)").all().map((column) => column.name);
    if (messageColumns.length && !messageColumns.includes("read_at")) {
        db.exec("ALTER TABLE messages ADD COLUMN read_at TEXT");
    }
    if (!purchaseColumns.includes("provider_completed")) {
        db.exec("ALTER TABLE service_purchases ADD COLUMN provider_completed INTEGER NOT NULL DEFAULT 0");
    }
    if (!purchaseColumns.includes("buyer_completed")) {
        db.exec("ALTER TABLE service_purchases ADD COLUMN buyer_completed INTEGER NOT NULL DEFAULT 0");
    }

    db.exec("UPDATE services SET price_unit = 'per booking' WHERE price_unit != 'per booking'");
    db.transaction = async (fn) => {
        db.exec("BEGIN");
        try {
            const result = await fn(db);
            db.exec("COMMIT");
            return result;
        } catch (error) {
            db.exec("ROLLBACK");
            throw error;
        }
    };
    return db;
}

const db = process.env.DATABASE_URL ? createPostgresDb() : setupSqliteDb();

module.exports = db;
module.exports.translateSqliteToPostgres = translateSqliteToPostgres;
